procedure InitializeComponent;
    begin
        self.groupBox1 := new System.Windows.Forms.GroupBox();
        self.textBox10 := new System.Windows.Forms.TextBox();
        self.label10 := new System.Windows.Forms.Label();
        self.textBox9 := new System.Windows.Forms.TextBox();
        self.label9 := new System.Windows.Forms.Label();
        self.textBox8 := new System.Windows.Forms.TextBox();
        self.label8 := new System.Windows.Forms.Label();
        self.textBox7 := new System.Windows.Forms.TextBox();
        self.label7 := new System.Windows.Forms.Label();
        self.textBox6 := new System.Windows.Forms.TextBox();
        self.label6 := new System.Windows.Forms.Label();
        self.textBox5 := new System.Windows.Forms.TextBox();
        self.label5 := new System.Windows.Forms.Label();
        self.textBox4 := new System.Windows.Forms.TextBox();
        self.label4 := new System.Windows.Forms.Label();
        self.textBox3 := new System.Windows.Forms.TextBox();
        self.label3 := new System.Windows.Forms.Label();
        self.textBox2 := new System.Windows.Forms.TextBox();
        self.label2 := new System.Windows.Forms.Label();
        self.textBox1 := new System.Windows.Forms.TextBox();
        self.label1 := new System.Windows.Forms.Label();
        self.groupBox2 := new System.Windows.Forms.GroupBox();
        self.textBox12 := new System.Windows.Forms.TextBox();
        self.textBox11 := new System.Windows.Forms.TextBox();
        self.label12 := new System.Windows.Forms.Label();
        self.label11 := new System.Windows.Forms.Label();
        self.button1 := new System.Windows.Forms.Button();
        self.groupBox3 := new System.Windows.Forms.GroupBox();
        self.label18 := new System.Windows.Forms.Label();
        self.label15 := new System.Windows.Forms.Label();
        self.textBox16 := new System.Windows.Forms.TextBox();
        self.textBox14 := new System.Windows.Forms.TextBox();
        self.textBox15 := new System.Windows.Forms.TextBox();
        self.textBox13 := new System.Windows.Forms.TextBox();
        self.label17 := new System.Windows.Forms.Label();
        self.label14 := new System.Windows.Forms.Label();
        self.label16 := new System.Windows.Forms.Label();
        self.label13 := new System.Windows.Forms.Label();
        self.groupBox4 := new System.Windows.Forms.GroupBox();
        self.textBox20 := new System.Windows.Forms.TextBox();
        self.textBox19 := new System.Windows.Forms.TextBox();
        self.textBox18 := new System.Windows.Forms.TextBox();
        self.textBox17 := new System.Windows.Forms.TextBox();
        self.label22 := new System.Windows.Forms.Label();
        self.label21 := new System.Windows.Forms.Label();
        self.label20 := new System.Windows.Forms.Label();
        self.label19 := new System.Windows.Forms.Label();
        self.groupBox5 := new System.Windows.Forms.GroupBox();
        self.textBox21 := new System.Windows.Forms.TextBox();
        self.textBox22 := new System.Windows.Forms.TextBox();
        self.textBox23 := new System.Windows.Forms.TextBox();
        self.textBox24 := new System.Windows.Forms.TextBox();
        self.label23 := new System.Windows.Forms.Label();
        self.label24 := new System.Windows.Forms.Label();
        self.label25 := new System.Windows.Forms.Label();
        self.label26 := new System.Windows.Forms.Label();
        self.button2 := new System.Windows.Forms.Button();
        self.label27 := new System.Windows.Forms.Label();
        self.textBox25 := new System.Windows.Forms.TextBox();
        self.button3 := new System.Windows.Forms.Button();
        self.button4 := new System.Windows.Forms.Button();
        self.groupBox6 := new System.Windows.Forms.GroupBox();
        self.textBox26 := new System.Windows.Forms.TextBox();
        self.label28 := new System.Windows.Forms.Label();
        self.textBox27 := new System.Windows.Forms.TextBox();
        self.label29 := new System.Windows.Forms.Label();
        self.textBox28 := new System.Windows.Forms.TextBox();
        self.label30 := new System.Windows.Forms.Label();
        self.textBox29 := new System.Windows.Forms.TextBox();
        self.label31 := new System.Windows.Forms.Label();
        self.textBox30 := new System.Windows.Forms.TextBox();
        self.label32 := new System.Windows.Forms.Label();
        self.textBox31 := new System.Windows.Forms.TextBox();
        self.label33 := new System.Windows.Forms.Label();
        self.textBox32 := new System.Windows.Forms.TextBox();
        self.label34 := new System.Windows.Forms.Label();
        self.textBox33 := new System.Windows.Forms.TextBox();
        self.label35 := new System.Windows.Forms.Label();
        self.textBox34 := new System.Windows.Forms.TextBox();
        self.label36 := new System.Windows.Forms.Label();
        self.textBox35 := new System.Windows.Forms.TextBox();
        self.label37 := new System.Windows.Forms.Label();
        self.groupBox1.SuspendLayout();
        self.groupBox2.SuspendLayout();
        self.groupBox3.SuspendLayout();
        self.groupBox4.SuspendLayout();
        self.groupBox5.SuspendLayout();
        self.groupBox6.SuspendLayout();
        self.SuspendLayout();
        // 
        // groupBox1
        // 
        self.groupBox1.Controls.Add(self.textBox10);
        self.groupBox1.Controls.Add(self.label10);
        self.groupBox1.Controls.Add(self.textBox9);
        self.groupBox1.Controls.Add(self.label9);
        self.groupBox1.Controls.Add(self.textBox8);
        self.groupBox1.Controls.Add(self.label8);
        self.groupBox1.Controls.Add(self.textBox7);
        self.groupBox1.Controls.Add(self.label7);
        self.groupBox1.Controls.Add(self.textBox6);
        self.groupBox1.Controls.Add(self.label6);
        self.groupBox1.Controls.Add(self.textBox5);
        self.groupBox1.Controls.Add(self.label5);
        self.groupBox1.Controls.Add(self.textBox4);
        self.groupBox1.Controls.Add(self.label4);
        self.groupBox1.Controls.Add(self.textBox3);
        self.groupBox1.Controls.Add(self.label3);
        self.groupBox1.Controls.Add(self.textBox2);
        self.groupBox1.Controls.Add(self.label2);
        self.groupBox1.Controls.Add(self.textBox1);
        self.groupBox1.Controls.Add(self.label1);
        self.groupBox1.Location := new System.Drawing.Point(13, 12);
        self.groupBox1.Name := 'groupBox1';
        self.groupBox1.Size := new System.Drawing.Size(459, 84);
        self.groupBox1.TabIndex := 0;
        self.groupBox1.TabStop := false;
        self.groupBox1.Text := 'Исходный массив';
        // 
        // textBox10
        // 
        self.textBox10.Location := new System.Drawing.Point(403, 47);
        self.textBox10.Name := 'textBox10';
        self.textBox10.Size := new System.Drawing.Size(38, 20);
        self.textBox10.TabIndex := 1;
        // 
        // label10
        // 
        self.label10.Location := new System.Drawing.Point(403, 16);
        self.label10.Name := 'label10';
        self.label10.Size := new System.Drawing.Size(38, 23);
        self.label10.TabIndex := 0;
        self.label10.Text := '10';
        self.label10.TextAlign := System.Drawing.ContentAlignment.MiddleCenter;
        // 
        // textBox9
        // 
        self.textBox9.Location := new System.Drawing.Point(359, 47);
        self.textBox9.Name := 'textBox9';
        self.textBox9.Size := new System.Drawing.Size(38, 20);
        self.textBox9.TabIndex := 1;
        // 
        // label9
        // 
        self.label9.Location := new System.Drawing.Point(359, 16);
        self.label9.Name := 'label9';
        self.label9.Size := new System.Drawing.Size(38, 23);
        self.label9.TabIndex := 0;
        self.label9.Text := '9';
        self.label9.TextAlign := System.Drawing.ContentAlignment.MiddleCenter;
        // 
        // textBox8
        // 
        self.textBox8.Location := new System.Drawing.Point(315, 47);
        self.textBox8.Name := 'textBox8';
        self.textBox8.Size := new System.Drawing.Size(38, 20);
        self.textBox8.TabIndex := 1;
        // 
        // label8
        // 
        self.label8.Location := new System.Drawing.Point(315, 16);
        self.label8.Name := 'label8';
        self.label8.Size := new System.Drawing.Size(38, 23);
        self.label8.TabIndex := 0;
        self.label8.Text := '8';
        self.label8.TextAlign := System.Drawing.ContentAlignment.MiddleCenter;
        // 
        // textBox7
        // 
        self.textBox7.Location := new System.Drawing.Point(271, 47);
        self.textBox7.Name := 'textBox7';
        self.textBox7.Size := new System.Drawing.Size(38, 20);
        self.textBox7.TabIndex := 1;
        // 
        // label7
        // 
        self.label7.Location := new System.Drawing.Point(271, 16);
        self.label7.Name := 'label7';
        self.label7.Size := new System.Drawing.Size(38, 23);
        self.label7.TabIndex := 0;
        self.label7.Text := '7';
        self.label7.TextAlign := System.Drawing.ContentAlignment.MiddleCenter;
        // 
        // textBox6
        // 
        self.textBox6.Location := new System.Drawing.Point(227, 47);
        self.textBox6.Name := 'textBox6';
        self.textBox6.Size := new System.Drawing.Size(38, 20);
        self.textBox6.TabIndex := 1;
        // 
        // label6
        // 
        self.label6.Location := new System.Drawing.Point(227, 16);
        self.label6.Name := 'label6';
        self.label6.Size := new System.Drawing.Size(38, 23);
        self.label6.TabIndex := 0;
        self.label6.Text := '6';
        self.label6.TextAlign := System.Drawing.ContentAlignment.MiddleCenter;
        // 
        // textBox5
        // 
        self.textBox5.Location := new System.Drawing.Point(183, 47);
        self.textBox5.Name := 'textBox5';
        self.textBox5.Size := new System.Drawing.Size(38, 20);
        self.textBox5.TabIndex := 1;
        // 
        // label5
        // 
        self.label5.Location := new System.Drawing.Point(183, 16);
        self.label5.Name := 'label5';
        self.label5.Size := new System.Drawing.Size(38, 23);
        self.label5.TabIndex := 0;
        self.label5.Text := '5';
        self.label5.TextAlign := System.Drawing.ContentAlignment.MiddleCenter;
        // 
        // textBox4
        // 
        self.textBox4.Location := new System.Drawing.Point(139, 47);
        self.textBox4.Name := 'textBox4';
        self.textBox4.Size := new System.Drawing.Size(38, 20);
        self.textBox4.TabIndex := 1;
        // 
        // label4
        // 
        self.label4.Location := new System.Drawing.Point(139, 16);
        self.label4.Name := 'label4';
        self.label4.Size := new System.Drawing.Size(38, 23);
        self.label4.TabIndex := 0;
        self.label4.Text := '4';
        self.label4.TextAlign := System.Drawing.ContentAlignment.MiddleCenter;
        // 
        // textBox3
        // 
        self.textBox3.Location := new System.Drawing.Point(95, 47);
        self.textBox3.Name := 'textBox3';
        self.textBox3.Size := new System.Drawing.Size(38, 20);
        self.textBox3.TabIndex := 1;
        // 
        // label3
        // 
        self.label3.Location := new System.Drawing.Point(95, 16);
        self.label3.Name := 'label3';
        self.label3.Size := new System.Drawing.Size(38, 23);
        self.label3.TabIndex := 0;
        self.label3.Text := '3';
        self.label3.TextAlign := System.Drawing.ContentAlignment.MiddleCenter;
        // 
        // textBox2
        // 
        self.textBox2.Location := new System.Drawing.Point(51, 47);
        self.textBox2.Name := 'textBox2';
        self.textBox2.Size := new System.Drawing.Size(38, 20);
        self.textBox2.TabIndex := 1;
        // 
        // label2
        // 
        self.label2.Location := new System.Drawing.Point(51, 16);
        self.label2.Name := 'label2';
        self.label2.Size := new System.Drawing.Size(38, 23);
        self.label2.TabIndex := 0;
        self.label2.Text := '2';
        self.label2.TextAlign := System.Drawing.ContentAlignment.MiddleCenter;
        // 
        // textBox1
        // 
        self.textBox1.Location := new System.Drawing.Point(7, 47);
        self.textBox1.Name := 'textBox1';
        self.textBox1.Size := new System.Drawing.Size(38, 20);
        self.textBox1.TabIndex := 1;
        // 
        // label1
        // 
        self.label1.Location := new System.Drawing.Point(7, 16);
        self.label1.Name := 'label1';
        self.label1.Size := new System.Drawing.Size(38, 23);
        self.label1.TabIndex := 0;
        self.label1.Text := '1';
        self.label1.TextAlign := System.Drawing.ContentAlignment.MiddleCenter;
        // 
        // groupBox2
        // 
        self.groupBox2.Controls.Add(self.textBox12);
        self.groupBox2.Controls.Add(self.textBox11);
        self.groupBox2.Controls.Add(self.label12);
        self.groupBox2.Controls.Add(self.label11);
        self.groupBox2.Location := new System.Drawing.Point(13, 104);
        self.groupBox2.Name := 'groupBox2';
        self.groupBox2.Size := new System.Drawing.Size(200, 55);
        self.groupBox2.TabIndex := 1;
        self.groupBox2.TabStop := false;
        self.groupBox2.Text := 'Границы диапазона';
        // 
        // textBox12
        // 
        self.textBox12.Location := new System.Drawing.Point(129, 22);
        self.textBox12.Name := 'textBox12';
        self.textBox12.Size := new System.Drawing.Size(47, 20);
        self.textBox12.TabIndex := 1;
        // 
        // textBox11
        // 
        self.textBox11.Location := new System.Drawing.Point(42, 22);
        self.textBox11.Name := 'textBox11';
        self.textBox11.Size := new System.Drawing.Size(47, 20);
        self.textBox11.TabIndex := 1;
        // 
        // label12
        // 
        self.label12.Location := new System.Drawing.Point(95, 20);
        self.label12.Name := 'label12';
        self.label12.Size := new System.Drawing.Size(28, 23);
        self.label12.TabIndex := 0;
        self.label12.Text := 'по';
        self.label12.TextAlign := System.Drawing.ContentAlignment.MiddleCenter;
        // 
        // label11
        // 
        self.label11.Location := new System.Drawing.Point(7, 20);
        self.label11.Name := 'label11';
        self.label11.Size := new System.Drawing.Size(28, 23);
        self.label11.TabIndex := 0;
        self.label11.Text := 'с';
        self.label11.TextAlign := System.Drawing.ContentAlignment.MiddleCenter;
        // 
        // button1
        // 
        self.button1.Location := new System.Drawing.Point(220, 104);
        self.button1.Name := 'button1';
        self.button1.Size := new System.Drawing.Size(116, 55);
        self.button1.TabIndex := 2;
        self.button1.Text := 'Заполнить массив целыми числами';
        self.button1.UseVisualStyleBackColor := true;
        self.button1.Click += button1_Click;
        // 
        // groupBox3
        // 
        self.groupBox3.Controls.Add(self.label18);
        self.groupBox3.Controls.Add(self.label15);
        self.groupBox3.Controls.Add(self.textBox16);
        self.groupBox3.Controls.Add(self.textBox14);
        self.groupBox3.Controls.Add(self.textBox15);
        self.groupBox3.Controls.Add(self.textBox13);
        self.groupBox3.Controls.Add(self.label17);
        self.groupBox3.Controls.Add(self.label14);
        self.groupBox3.Controls.Add(self.label16);
        self.groupBox3.Controls.Add(self.label13);
        self.groupBox3.Location := new System.Drawing.Point(20, 200);
        self.groupBox3.Name := 'groupBox3';
        self.groupBox3.Size := new System.Drawing.Size(330, 100);
        self.groupBox3.TabIndex := 3;
        self.groupBox3.TabStop := false;
        self.groupBox3.Text := '1';
        // 
        // label18
        // 
        self.label18.Location := new System.Drawing.Point(216, 49);
        self.label18.Name := 'label18';
        self.label18.Size := new System.Drawing.Size(62, 23);
        self.label18.TabIndex := 2;
        self.label18.Text := 'значение';
        self.label18.TextAlign := System.Drawing.ContentAlignment.MiddleCenter;
        // 
        // label15
        // 
        self.label15.Location := new System.Drawing.Point(216, 15);
        self.label15.Name := 'label15';
        self.label15.Size := new System.Drawing.Size(62, 23);
        self.label15.TabIndex := 2;
        self.label15.Text := 'значение';
        self.label15.TextAlign := System.Drawing.ContentAlignment.MiddleCenter;
        // 
        // textBox16
        // 
        self.textBox16.Location := new System.Drawing.Point(279, 53);
        self.textBox16.Name := 'textBox16';
        self.textBox16.Size := new System.Drawing.Size(39, 20);
        self.textBox16.TabIndex := 1;
        // 
        // textBox14
        // 
        self.textBox14.Location := new System.Drawing.Point(279, 19);
        self.textBox14.Name := 'textBox14';
        self.textBox14.Size := new System.Drawing.Size(39, 20);
        self.textBox14.TabIndex := 1;
        // 
        // textBox15
        // 
        self.textBox15.Location := new System.Drawing.Point(171, 52);
        self.textBox15.Name := 'textBox15';
        self.textBox15.Size := new System.Drawing.Size(39, 20);
        self.textBox15.TabIndex := 1;
        // 
        // textBox13
        // 
        self.textBox13.Location := new System.Drawing.Point(171, 18);
        self.textBox13.Name := 'textBox13';
        self.textBox13.Size := new System.Drawing.Size(39, 20);
        self.textBox13.TabIndex := 1;
        // 
        // label17
        // 
        self.label17.Location := new System.Drawing.Point(67, 49);
        self.label17.Name := 'label17';
        self.label17.Size := new System.Drawing.Size(115, 23);
        self.label17.TabIndex := 0;
        self.label17.Text := 'номер элемента';
        self.label17.TextAlign := System.Drawing.ContentAlignment.MiddleCenter;
        // 
        // label14
        // 
        self.label14.Location := new System.Drawing.Point(67, 15);
        self.label14.Name := 'label14';
        self.label14.Size := new System.Drawing.Size(115, 23);
        self.label14.TabIndex := 0;
        self.label14.Text := 'номер элемента';
        self.label14.TextAlign := System.Drawing.ContentAlignment.MiddleCenter;
        // 
        // label16
        // 
        self.label16.Location := new System.Drawing.Point(6, 50);
        self.label16.Name := 'label16';
        self.label16.Size := new System.Drawing.Size(66, 23);
        self.label16.TabIndex := 0;
        self.label16.Text := 'Максимум:';
        self.label16.TextAlign := System.Drawing.ContentAlignment.MiddleCenter;
        // 
        // label13
        // 
        self.label13.Location := new System.Drawing.Point(6, 16);
        self.label13.Name := 'label13';
        self.label13.Size := new System.Drawing.Size(66, 23);
        self.label13.TabIndex := 0;
        self.label13.Text := 'Минимум:';
        self.label13.TextAlign := System.Drawing.ContentAlignment.MiddleCenter;
        // 
        // groupBox4
        // 
        self.groupBox4.Controls.Add(self.textBox20);
        self.groupBox4.Controls.Add(self.textBox19);
        self.groupBox4.Controls.Add(self.textBox18);
        self.groupBox4.Controls.Add(self.textBox17);
        self.groupBox4.Controls.Add(self.label22);
        self.groupBox4.Controls.Add(self.label21);
        self.groupBox4.Controls.Add(self.label20);
        self.groupBox4.Controls.Add(self.label19);
        self.groupBox4.Location := new System.Drawing.Point(20, 315);
        self.groupBox4.Name := 'groupBox4';
        self.groupBox4.Size := new System.Drawing.Size(258, 127);
        self.groupBox4.TabIndex := 4;
        self.groupBox4.TabStop := false;
        self.groupBox4.Text := '2';
        // 
        // textBox20
        // 
        self.textBox20.Location := new System.Drawing.Point(140, 92);
        self.textBox20.Name := 'textBox20';
        self.textBox20.Size := new System.Drawing.Size(100, 20);
        self.textBox20.TabIndex := 1;
        // 
        // textBox19
        // 
        self.textBox19.Location := new System.Drawing.Point(140, 69);
        self.textBox19.Name := 'textBox19';
        self.textBox19.Size := new System.Drawing.Size(100, 20);
        self.textBox19.TabIndex := 1;
        // 
        // textBox18
        // 
        self.textBox18.Location := new System.Drawing.Point(140, 46);
        self.textBox18.Name := 'textBox18';
        self.textBox18.Size := new System.Drawing.Size(100, 20);
        self.textBox18.TabIndex := 1;
        // 
        // textBox17
        // 
        self.textBox17.Location := new System.Drawing.Point(140, 23);
        self.textBox17.Name := 'textBox17';
        self.textBox17.Size := new System.Drawing.Size(100, 20);
        self.textBox17.TabIndex := 1;
        // 
        // label22
        // 
        self.label22.Location := new System.Drawing.Point(7, 89);
        self.label22.Name := 'label22';
        self.label22.Size := new System.Drawing.Size(162, 23);
        self.label22.TabIndex := 0;
        self.label22.Text := 'Сумма отрицательных';
        self.label22.TextAlign := System.Drawing.ContentAlignment.MiddleLeft;
        // 
        // label21
        // 
        self.label21.Location := new System.Drawing.Point(7, 66);
        self.label21.Name := 'label21';
        self.label21.Size := new System.Drawing.Size(162, 23);
        self.label21.TabIndex := 0;
        self.label21.Text := 'Сумма положительных';
        self.label21.TextAlign := System.Drawing.ContentAlignment.MiddleLeft;
        // 
        // label20
        // 
        self.label20.Location := new System.Drawing.Point(7, 43);
        self.label20.Name := 'label20';
        self.label20.Size := new System.Drawing.Size(162, 23);
        self.label20.TabIndex := 0;
        self.label20.Text := 'Среднее значение';
        self.label20.TextAlign := System.Drawing.ContentAlignment.MiddleLeft;
        // 
        // label19
        // 
        self.label19.Location := new System.Drawing.Point(7, 20);
        self.label19.Name := 'label19';
        self.label19.Size := new System.Drawing.Size(162, 23);
        self.label19.TabIndex := 0;
        self.label19.Text := 'Сумма всех элементов';
        self.label19.TextAlign := System.Drawing.ContentAlignment.MiddleLeft;
        // 
        // groupBox5
        // 
        self.groupBox5.Controls.Add(self.textBox21);
        self.groupBox5.Controls.Add(self.textBox22);
        self.groupBox5.Controls.Add(self.textBox23);
        self.groupBox5.Controls.Add(self.textBox24);
        self.groupBox5.Controls.Add(self.label23);
        self.groupBox5.Controls.Add(self.label24);
        self.groupBox5.Controls.Add(self.label25);
        self.groupBox5.Controls.Add(self.label26);
        self.groupBox5.Location := new System.Drawing.Point(290, 315);
        self.groupBox5.Name := 'groupBox5';
        self.groupBox5.Size := new System.Drawing.Size(264, 127);
        self.groupBox5.TabIndex := 4;
        self.groupBox5.TabStop := false;
        self.groupBox5.Text := '3';
        // 
        // textBox21
        // 
        self.textBox21.Location := new System.Drawing.Point(189, 92);
        self.textBox21.Name := 'textBox21';
        self.textBox21.Size := new System.Drawing.Size(58, 20);
        self.textBox21.TabIndex := 1;
        // 
        // textBox22
        // 
        self.textBox22.Location := new System.Drawing.Point(189, 69);
        self.textBox22.Name := 'textBox22';
        self.textBox22.Size := new System.Drawing.Size(58, 20);
        self.textBox22.TabIndex := 1;
        // 
        // textBox23
        // 
        self.textBox23.Location := new System.Drawing.Point(189, 46);
        self.textBox23.Name := 'textBox23';
        self.textBox23.Size := new System.Drawing.Size(58, 20);
        self.textBox23.TabIndex := 1;
        // 
        // textBox24
        // 
        self.textBox24.Location := new System.Drawing.Point(189, 23);
        self.textBox24.Name := 'textBox24';
        self.textBox24.Size := new System.Drawing.Size(58, 20);
        self.textBox24.TabIndex := 1;
        // 
        // label23
        // 
        self.label23.Location := new System.Drawing.Point(7, 89);
        self.label23.Name := 'label23';
        self.label23.Size := new System.Drawing.Size(174, 23);
        self.label23.TabIndex := 0;
        self.label23.Text := 'Кол-во отрицательных нечётных';
        self.label23.TextAlign := System.Drawing.ContentAlignment.MiddleLeft;
        // 
        // label24
        // 
        self.label24.Location := new System.Drawing.Point(7, 66);
        self.label24.Name := 'label24';
        self.label24.Size := new System.Drawing.Size(162, 23);
        self.label24.TabIndex := 0;
        self.label24.Text := 'Кол-во отрицательных чётных';
        self.label24.TextAlign := System.Drawing.ContentAlignment.MiddleLeft;
        // 
        // label25
        // 
        self.label25.Location := new System.Drawing.Point(7, 43);
        self.label25.Name := 'label25';
        self.label25.Size := new System.Drawing.Size(174, 23);
        self.label25.TabIndex := 0;
        self.label25.Text := 'Кол-во положительных нечётных';
        self.label25.TextAlign := System.Drawing.ContentAlignment.MiddleLeft;
        // 
        // label26
        // 
        self.label26.Location := new System.Drawing.Point(7, 20);
        self.label26.Name := 'label26';
        self.label26.Size := new System.Drawing.Size(162, 23);
        self.label26.TabIndex := 0;
        self.label26.Text := 'Кол-во положительных четных';
        self.label26.TextAlign := System.Drawing.ContentAlignment.MiddleLeft;
        // 
        // button2
        // 
        self.button2.Location := new System.Drawing.Point(372, 234);
        self.button2.Name := 'button2';
        self.button2.Size := new System.Drawing.Size(115, 52);
        self.button2.TabIndex := 5;
        self.button2.Text := 'Статистика';
        self.button2.UseVisualStyleBackColor := true;
        self.button2.Click += button2_Click;
        // 
        // label27
        // 
        self.label27.Location := new System.Drawing.Point(20, 454);
        self.label27.Name := 'label27';
        self.label27.Size := new System.Drawing.Size(193, 23);
        self.label27.TabIndex := 0;
        self.label27.Text := 'Произведение элементов массива';
        self.label27.TextAlign := System.Drawing.ContentAlignment.MiddleLeft;
        // 
        // textBox25
        // 
        self.textBox25.Location := new System.Drawing.Point(228, 457);
        self.textBox25.Name := 'textBox25';
        self.textBox25.Size := new System.Drawing.Size(156, 20);
        self.textBox25.TabIndex := 1;
        // 
        // button3
        // 
        self.button3.Location := new System.Drawing.Point(12, 497);
        self.button3.Name := 'button3';
        self.button3.Size := new System.Drawing.Size(115, 52);
        self.button3.TabIndex := 5;
        self.button3.Text := 'Реверс массива';
        self.button3.UseVisualStyleBackColor := true;
        self.button3.Click += button3_Click;
        // 
        // button4
        // 
        self.button4.Location := new System.Drawing.Point(142, 497);
        self.button4.Name := 'button4';
        self.button4.Size := new System.Drawing.Size(115, 52);
        self.button4.TabIndex := 5;
        self.button4.Text := 'Сортировка массива';
        self.button4.UseVisualStyleBackColor := true;
        self.button4.Click += button4_Click;
        // 
        // groupBox6
        // 
        self.groupBox6.Controls.Add(self.textBox26);
        self.groupBox6.Controls.Add(self.label28);
        self.groupBox6.Controls.Add(self.textBox27);
        self.groupBox6.Controls.Add(self.label29);
        self.groupBox6.Controls.Add(self.textBox28);
        self.groupBox6.Controls.Add(self.label30);
        self.groupBox6.Controls.Add(self.textBox29);
        self.groupBox6.Controls.Add(self.label31);
        self.groupBox6.Controls.Add(self.textBox30);
        self.groupBox6.Controls.Add(self.label32);
        self.groupBox6.Controls.Add(self.textBox31);
        self.groupBox6.Controls.Add(self.label33);
        self.groupBox6.Controls.Add(self.textBox32);
        self.groupBox6.Controls.Add(self.label34);
        self.groupBox6.Controls.Add(self.textBox33);
        self.groupBox6.Controls.Add(self.label35);
        self.groupBox6.Controls.Add(self.textBox34);
        self.groupBox6.Controls.Add(self.label36);
        self.groupBox6.Controls.Add(self.textBox35);
        self.groupBox6.Controls.Add(self.label37);
        self.groupBox6.Location := new System.Drawing.Point(13, 569);
        self.groupBox6.Name := 'groupBox6';
        self.groupBox6.Size := new System.Drawing.Size(459, 84);
        self.groupBox6.TabIndex := 0;
        self.groupBox6.TabStop := false;
        self.groupBox6.Text := 'Массив-результат';
        // 
        // textBox26
        // 
        self.textBox26.Location := new System.Drawing.Point(403, 47);
        self.textBox26.Name := 'textBox26';
        self.textBox26.Size := new System.Drawing.Size(38, 20);
        self.textBox26.TabIndex := 1;
        // 
        // label28
        // 
        self.label28.Location := new System.Drawing.Point(403, 16);
        self.label28.Name := 'label28';
        self.label28.Size := new System.Drawing.Size(38, 23);
        self.label28.TabIndex := 0;
        self.label28.Text := '10';
        self.label28.TextAlign := System.Drawing.ContentAlignment.MiddleCenter;
        // 
        // textBox27
        // 
        self.textBox27.Location := new System.Drawing.Point(359, 47);
        self.textBox27.Name := 'textBox27';
        self.textBox27.Size := new System.Drawing.Size(38, 20);
        self.textBox27.TabIndex := 1;
        // 
        // label29
        // 
        self.label29.Location := new System.Drawing.Point(359, 16);
        self.label29.Name := 'label29';
        self.label29.Size := new System.Drawing.Size(38, 23);
        self.label29.TabIndex := 0;
        self.label29.Text := '9';
        self.label29.TextAlign := System.Drawing.ContentAlignment.MiddleCenter;
        // 
        // textBox28
        // 
        self.textBox28.Location := new System.Drawing.Point(315, 47);
        self.textBox28.Name := 'textBox28';
        self.textBox28.Size := new System.Drawing.Size(38, 20);
        self.textBox28.TabIndex := 1;
        // 
        // label30
        // 
        self.label30.Location := new System.Drawing.Point(315, 16);
        self.label30.Name := 'label30';
        self.label30.Size := new System.Drawing.Size(38, 23);
        self.label30.TabIndex := 0;
        self.label30.Text := '8';
        self.label30.TextAlign := System.Drawing.ContentAlignment.MiddleCenter;
        // 
        // textBox29
        // 
        self.textBox29.Location := new System.Drawing.Point(271, 47);
        self.textBox29.Name := 'textBox29';
        self.textBox29.Size := new System.Drawing.Size(38, 20);
        self.textBox29.TabIndex := 1;
        // 
        // label31
        // 
        self.label31.Location := new System.Drawing.Point(271, 16);
        self.label31.Name := 'label31';
        self.label31.Size := new System.Drawing.Size(38, 23);
        self.label31.TabIndex := 0;
        self.label31.Text := '7';
        self.label31.TextAlign := System.Drawing.ContentAlignment.MiddleCenter;
        // 
        // textBox30
        // 
        self.textBox30.Location := new System.Drawing.Point(227, 47);
        self.textBox30.Name := 'textBox30';
        self.textBox30.Size := new System.Drawing.Size(38, 20);
        self.textBox30.TabIndex := 1;
        // 
        // label32
        // 
        self.label32.Location := new System.Drawing.Point(227, 16);
        self.label32.Name := 'label32';
        self.label32.Size := new System.Drawing.Size(38, 23);
        self.label32.TabIndex := 0;
        self.label32.Text := '6';
        self.label32.TextAlign := System.Drawing.ContentAlignment.MiddleCenter;
        // 
        // textBox31
        // 
        self.textBox31.Location := new System.Drawing.Point(183, 47);
        self.textBox31.Name := 'textBox31';
        self.textBox31.Size := new System.Drawing.Size(38, 20);
        self.textBox31.TabIndex := 1;
        // 
        // label33
        // 
        self.label33.Location := new System.Drawing.Point(183, 16);
        self.label33.Name := 'label33';
        self.label33.Size := new System.Drawing.Size(38, 23);
        self.label33.TabIndex := 0;
        self.label33.Text := '5';
        self.label33.TextAlign := System.Drawing.ContentAlignment.MiddleCenter;
        // 
        // textBox32
        // 
        self.textBox32.Location := new System.Drawing.Point(139, 47);
        self.textBox32.Name := 'textBox32';
        self.textBox32.Size := new System.Drawing.Size(38, 20);
        self.textBox32.TabIndex := 1;
        // 
        // label34
        // 
        self.label34.Location := new System.Drawing.Point(139, 16);
        self.label34.Name := 'label34';
        self.label34.Size := new System.Drawing.Size(38, 23);
        self.label34.TabIndex := 0;
        self.label34.Text := '4';
        self.label34.TextAlign := System.Drawing.ContentAlignment.MiddleCenter;
        // 
        // textBox33
        // 
        self.textBox33.Location := new System.Drawing.Point(95, 47);
        self.textBox33.Name := 'textBox33';
        self.textBox33.Size := new System.Drawing.Size(38, 20);
        self.textBox33.TabIndex := 1;
        // 
        // label35
        // 
        self.label35.Location := new System.Drawing.Point(95, 16);
        self.label35.Name := 'label35';
        self.label35.Size := new System.Drawing.Size(38, 23);
        self.label35.TabIndex := 0;
        self.label35.Text := '3';
        self.label35.TextAlign := System.Drawing.ContentAlignment.MiddleCenter;
        // 
        // textBox34
        // 
        self.textBox34.Location := new System.Drawing.Point(51, 47);
        self.textBox34.Name := 'textBox34';
        self.textBox34.Size := new System.Drawing.Size(38, 20);
        self.textBox34.TabIndex := 1;
        // 
        // label36
        // 
        self.label36.Location := new System.Drawing.Point(51, 16);
        self.label36.Name := 'label36';
        self.label36.Size := new System.Drawing.Size(38, 23);
        self.label36.TabIndex := 0;
        self.label36.Text := '2';
        self.label36.TextAlign := System.Drawing.ContentAlignment.MiddleCenter;
        // 
        // textBox35
        // 
        self.textBox35.Location := new System.Drawing.Point(7, 47);
        self.textBox35.Name := 'textBox35';
        self.textBox35.Size := new System.Drawing.Size(38, 20);
        self.textBox35.TabIndex := 1;
        // 
        // label37
        // 
        self.label37.Location := new System.Drawing.Point(7, 16);
        self.label37.Name := 'label37';
        self.label37.Size := new System.Drawing.Size(38, 23);
        self.label37.TabIndex := 0;
        self.label37.Text := '1';
        self.label37.TextAlign := System.Drawing.ContentAlignment.MiddleCenter;
        // 
        // Form1
        // 
        self.ClientSize := new System.Drawing.Size(560, 683);
        self.Controls.Add(self.textBox25);
        self.Controls.Add(self.button4);
        self.Controls.Add(self.button3);
        self.Controls.Add(self.button2);
        self.Controls.Add(self.groupBox5);
        self.Controls.Add(self.groupBox4);
        self.Controls.Add(self.groupBox3);
        self.Controls.Add(self.label27);
        self.Controls.Add(self.button1);
        self.Controls.Add(self.groupBox2);
        self.Controls.Add(self.groupBox6);
        self.Controls.Add(self.groupBox1);
        self.Name := 'Form1';
        self.Text := 'Массивы';
        self.Load += Form1_Load;
        self.groupBox1.ResumeLayout(false);
        self.groupBox1.PerformLayout();
        self.groupBox2.ResumeLayout(false);
        self.groupBox2.PerformLayout();
        self.groupBox3.ResumeLayout(false);
        self.groupBox3.PerformLayout();
        self.groupBox4.ResumeLayout(false);
        self.groupBox4.PerformLayout();
        self.groupBox5.ResumeLayout(false);
        self.groupBox5.PerformLayout();
        self.groupBox6.ResumeLayout(false);
        self.groupBox6.PerformLayout();
        self.ResumeLayout(false);
        self.PerformLayout();
    end;
